name: "Workflow Timer"
description: "Worfklow timer..."

runs:
  using: "composite"
  steps:
    - run: "echo Fredrik och Ricki Testar"
      shell: bash
    - uses: actions/github-script@v6
      id: duration
      with:
        script: |
          const currentTime = new Date().getTime();
          const currentRun = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          const startedAt = currentRun.data.run_started_at
          const durationInMillis = currentTime - new Date(startedAt).getTime();
          return {
            durationInMillis: durationInMillis,
            workflowId: currentRun.data.workflow_id
          }
    - run: |
        echo "${{ steps.duration.outputs.result }}"
      shell: bash
    - uses: actions/github-script@v6
      with:
        script: |
          const runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: context.workflow
          });
          console.log(runs)
