name: "Workflow Timer"
description: "Measures the duration of the workflow and compares it to the duration of historical runs."
branding:
  icon: "clock"
  color: "green"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
