name: 'Workflow Timer'
description:
  'Measures the duration of the workflow and compares it to the duration of
  historical runs.'
branding:
  icon: 'clock'
  color: 'green'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/main-index.js'
  post: 'dist/post-index.js'
