name: "Workflow Timer"
description: "Worfklow timer..."

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      id: duration
      with:
        script: |
          const currentTime = new Date().getTime();
          const currentRun = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          const startedAt = currentRun.data.run_started_at
          const durationInMillis = currentTime - new Date(startedAt).getTime();
          
          const workflowId = currentRun.data.workflow_id
          const historical_runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflowId
          });  
          console.log(historical_runs.data)
          console.log(durationInMillis)
