name: "Workflow Timer"
description: "Worfklow timer..."

runs:
  using: "composite"
  steps:
    - run: "echo Fredrik och Ricki Testar"
      shell: bash
    - uses: actions/github-script@v6
      id: startTime
      with:
        script: |
          const currentRun = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          return currentRun.data.run_started_at
    - run: |
        echo "${{ steps.startTime.outputs.result }}"
      shell: bash
