name: 'Workflow Timer'
description:
  'Measures the duration of the workflow and compares it to the duration of
  historical runs.'
branding:
  icon: 'clock'
  color: 'green'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  compareBranch:
    description:
      'Branch to compare workflow durations with (typically your default
      branch).'
    required: false
    default: 'main'
  percentageThreshold:
    description:
      'Minimum percentage change required to post a comment. Must be a
      non-negative number. Set to 0 to always post comments.'
    required: false
    default: '0'
runs:
  using: 'node24'
  main: 'dist/index.js'
