name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
  runs-on: ubuntu-latest
  needs: publish
  permissions:
    contents: write
  steps:
    - uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
