name: release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
  runs-on: ubuntu-latest
  steps:
    - uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
